#!/bin/bash

# helper function

# https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
__get_script_dir() {
    caller_context=($(caller))
    #SOURCE="${BASH_SOURCE[0]}"
    SOURCE=${caller_context[1]}
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
      DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
      SOURCE="$(readlink "$SOURCE")"
      [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    echo $DIR
}

__which_content() {
    funcname=$1
    which "${funcname}" > /dev/null 2>&1
    if [[ "$?" != 0  ]]; then
        echo "Error: \"${funcname}\" function not found."
        return 1
    fi
    which "${funcname}" | sed -e '1,2d' | head -n -1 | awk '{$1=$1};1'
}

#set -o allexport
#source /etc/home-config-info
#set +o allexport

# https://stackoverflow.com/questions/5014823/how-can-i-profile-a-bash-shell-script-slow-startup
# PS4='+ $(date "+%s.%N")\011 '
# exec 3>&2 2>/tmp/bashstart.$$.log
# set -x


BASH_MYBASH_SCRIPT_DIR=$(__get_script_dir)
# source all files in bash/, private/bash
# source main.sh first then other file, order by find command :)
# need to add SCRIPT_DIR=$(__get_script_dir) to restore value back, in case get replace by source
source "${BASH_MYBASH_SCRIPT_DIR}/bash/main.sh";
for i in $(find "${BASH_MYBASH_SCRIPT_DIR}"/bash/ -type f -iname '*.sh' | grep -v main.sh); do
    source "${i}";
done

source "${BASH_MYBASH_SCRIPT_DIR}/private/bash/main.sh";
for i in $(find "${BASH_MYBASH_SCRIPT_DIR}"/private/bash/ -type f -iname '*.sh' | grep -v main.sh); do
    source "${i}";
done

# set +x
# exec 2>&3 3>&-
# path

# path in home-config
export PATH="${BASH_MYBASH_SCRIPT_DIR}"/bin:"$PATH"
export PATH="${BASH_MYBASH_SCRIPT_DIR}"/private/bin:"$PATH"
