- hosts: localhost
  connection: local
  become: no
  tasks:
  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest
  - name: install dnf package
    tags:
    - dnf
    dnf:
      name:
      - emacs
      - tmux
      - gnome-tweaks
      - cowsay
      - zstd
      - the_silver_searcher
      - fd-find
      - fzf
      - wine
      - ncdu
      - autossh
      - xsel # for tmux
      - keepassxc
      - inotify-tools
      - pv
      - age
      - dnf-plugin-system-upgrade
      - openssl
      - xset
      - golang-github-google-jsonnet
      - pandoc
      - ripgrep
      - golang-sigs-k8s-kustomize
      - remmina
      # for emacs builds
      - autoconf
      - texinfo
      - gtk3-devel
      - webkit2gtk3-devel
      - libgccgit-devel
      - jansson-devel
      - giflib-devel
      - gnutls-devel
      - libXpm-devel
      - libjpeg-turbo-devel
      - ncurses-devel
      # require by emacs gui (get gtk error)
      - xapps
      # computer language
      - ruby
      - golang
      - nodejs
      - npm
      - yarnpkg
      state: present
    become: yes

  - name: add flathub to flatpak repo
    tags: flatpak
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: user

  - name: install flatpak package
    tags: flatpak
    flatpak:
      name: '{{ item }}'
      method: user
      state: present
    with_items:
    - com.discordapp.Discord
    - com.spotify.Client
    - com.slack.Slack
    - us.zoom.Zoom

  - name: download google chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      dest: ~/Downloads
  - name: add google rpm key
    rpm_key:
      state: present
      key: https://dl.google.com/linux/linux_signing_key.pub
      fingerprint: 4CCA 1EAF 950C EE4A B839 76DC A040 830F 7FAC 5991

    become: yes

  - name: install google chrome with dnf
    dnf:
      name: '{{ ansible_user_dir }}/Downloads/google-chrome-stable_current_x86_64.rpm'
      state: present
    become: yes

  - name: import rpmfusion free key
    rpm_key:
      state: present
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      fingerprint: E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E
    become: yes

  - name: import rpmfusion nonfree key
    rpm_key:
      state: present
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
      fingerprint: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65
    become: yes

  - name: install rpmfusion free and nonfree
    dnf:
      name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      state: present
    become: yes

  - name: install nvidia driver
    dnf:
      name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      state: present
    become: yes

  - name: ensure fonts dir
    file:
      path: ~/.local/share/fonts
      state: directory

  - name: download liberation-mono font
    get_url:
      url: https://www.fontsquirrel.com/fonts/download/liberation-mono
      dest: ~/Downloads/liberation-mono.zip

  - name: unzip downloaded fonts
    unarchive:
      src: ~/Downloads/liberation-mono.zip
      dest: ~/.local/share/fonts/

  - name: refresh front cache
    command: fc-cache -v -f

  - name: enable emacs server now
    systemd:
      name: emacs
      state: started
      enabled: yes
      scope: user

  - name: symlink key
    file:
      src: ~/myhome/keys
      dest: ~/.keys
      state: link

  - name: downloads pixel-saver
    tags: gnome
    git:
      repo: https://github.com/pixel-saver/pixel-saver
      dest: ~/.local/share/pixel-saver
      version: tags/1.24

  - name: ensure ~/.local/share/gnome-shell/extensions exists
    tags: gnome
    file:
      path: ~/.local/share/gnome-shell/extensions
      state: directory

  - name: symlink to gnome-shell extension dir
    tags: gnome
    file:
      src: '~/.local/share/pixel-saver/pixel-saver@deadalnix.me'
      dest: '~/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me'
      state: link

  - name: install kubectl
    tags: kubectl
    get_url:
      url: https://dl.k8s.io/release/v1.18.15/bin/linux/amd64/kubectl
      dest: ~/.local/bin
      mode: '0755'

  - name: ensure user bash_completion.d dir
    file:
      path: ~/.bash_completion.d
      state: directory

  - name: export kubectl bash completion
    tags:
    - kubectl
    - single
    command: bash -c 'kubectl completion bash > ~/.bash_completion.d/kubectl.bash'

  - name: install kubelogin
    tags: kubectl
    get_url:
      url: https://github.com/int128/kubelogin/releases/download/v1.22.1/kubelogin_linux_amd64.zip
      dest: ~/Downloads

  - name: extract kubelogin
    tags: kubectl
    unarchive:
      src: ~/Downloads/kubelogin_linux_amd64.zip
      dest: ~/.local/bin/
      exclude: LICENSE

  - name: rename kubelogin to kubectl-oidc_login
    tags: kubectl
    command: mv ~/.local/bin/kubelogin ~/.local/bin/kubectl-oidc_login

  - name: ensure ~/.kube dir
    tags: kubectl
    file:
      path: ~/.kube
      mode: '0700'
      state: directory

  - name: symlink kube config
    tags: kubectl
    file:
      src: '{{playbook_dir}}/private/kube/config'
      dest: ~/.kube/config
      state: link

  - name: downloads kubectx
    tags: kubectx
    git:
      repo: https://github.com/ahmetb/kubectx
      dest: ~/.local/share/kubectx
      version: tags/v0.8.0

  - name: symlink kubectx kubens
    tags: kubectx
    file:
      src: '~/.local/share/kubectx/{{ item }}'
      dest: '~/.local/bin/{{ item }}'
      state: link
    with_items:
    - kubectx
    - kubens

  - name: ensure ~/.bash_completion.d dir
    tags: kubectx
    file:
      path: ~/.bash_completion.d
      state: directory

  - name: symlink kubectx kubens bash completion
    tags: kubectx
    file:
      src: '~/.local/share/kubectx/completion/{{item}}.bash'
      dest: '~/.bash_completion.d/{{ item }}.bash'
      state: link
    with_items:
    - kubectx
    - kubens

  - name: install python dependency
    tags: pip
    pip:
      name:
      - boto
      - boto3
      - ipython
      - pipenv
      - poetry
      - sshuttle
      - yapf
      - yq
      - 'python-language-server[all]'
      - glances
      state: latest
      extra_args: --user

  - name: install aws-cli v2
    tags: awscli
    get_url:
      url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: ~/Downloads/awscliv2.zip
  - name: unzip downloaded fonts
    tags: awscli
    unarchive:
      src: ~/Downloads/awscliv2.zip
      dest: /tmp
  - name: run install commands
    tags: awscli
    command: /tmp/aws/install -i ~/.local/share/aws-cli -b ~/.local/bin

  - name: install pyenv
    tags: pyenv
    git:
      repo: https://github.com/pyenv/pyenv
      dest: ~/.local/share/pyenv
      version: tags/v1.2.23

  - name: install pyenv-virtualenv
    tags: pyenv
    git:
      repo: https://github.com/pyenv/pyenv-virtualenv
      dest: ~/.local/share/pyenv/plugins/pyenv-virtualenv
      version: tags/v1.1.5

  - name: add docker repo
    tags: docker
    command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    become: yes
  - name: install docker
    tags: docker
    dnf:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present
    become: yes
  - name: start docker
    tags: docker
    systemd:
      name: docker
      state: started
      enabled: yes
    become: yes

  - name: add user to docker group
    tags: docker
    command: usermod -aG docker "{{ ansible_user_id }}"
    become: yes

  - name: import keybase key
    tags: keybase
    rpm_key:
      state: present
      key: https://keybase.io/docs/server_security/code_signing_key.asc
      fingerprint: 222B 85B0 F90B E2D2 4CFE B93F 4748 4E50 656D 16C7
    become: yes

  - name: add harshicorp
    tags: docker
    command: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    become: yes

  - name: install hashicorp binary
    tags: docker
    dnf:
      name:
      - vault
      - terraform
      - packer
      state: present
    become: yes

  - name: install keybase repo
    tags: keybase
    dnf:
      name: https://prerelease.keybase.io/keybase_amd64.rpm
      state: present
    become: yes

  - name: downloads helm
    tags: helm
    get_url:
      url: https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz
      dest: /tmp/helm.tar.gz
      checksum: sha256:01b317c506f8b6ad60b11b1dc3f093276bb703281cb1ae01132752253ec706a2

  - name: unzip helm
    tags: helm
    unarchive:
      src: /tmp/helm.tar.gz
      dest: /tmp

  - name: move bin helm to ~/.local/bin
    tags: helm
    copy:
      src: /tmp/linux-amd64/helm
      dest: ~/.local/bin
      mode: '0755'

  - name: symlink emacsclient
    tags: emacsclient
    file:
      src: '{{playbook_dir}}/desktop/emacsclient.desktop'
      dest: ~/.local/share/applications/emacsclient.desktop
      state: link
